# Generated by Django 4.2.10 on 2024-04-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0003_alter_userrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LDAPGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth_app.ldapgroup')),
            ],
            options={
                'unique_together': {('group', 'username')},
            },
        ),
    ]
