# Generated by Django 4.2.11 on 2024-05-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0004_ldapgroup_ldapgroupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth_app.role')),
            ],
        ),
    ]
