# Generated by Django 4.2.11 on 2024-05-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0005_grouproleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouproleassignment',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
