# Generated by Django 4.2.11 on 2024-05-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0006_alter_grouproleassignment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouproleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth_app.role'),
        ),
    ]
