# Generated by Django 4.2.11 on 2024-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0007_alter_grouproleassignment_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouproleassignment',
            name='group',
        ),
        migrations.AddField(
            model_name='grouproleassignment',
            name='group_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
