# Generated by Django 4.2.11 on 2024-05-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0009_alter_grouproleassignment_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouproleassignment',
            old_name='group_name',
            new_name='group',
        ),
    ]
