# Generated by Django 4.2.9 on 2024-03-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider1_api', '0003_provider_kubeconfig_data_alter_provider_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='tenant_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
