# Generated by Django 4.2.9 on 2024-03-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider1_api', '0004_provider_password_provider_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='auth_url',
            field=models.URLField(null=True),
        ),
    ]
