# Generated by Django 4.2.9 on 2024-03-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider1_api', '0005_provider_auth_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='password',
            new_name='openStackuser',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='username',
            new_name='openstackpassword',
        ),
    ]
