# Generated by Django 5.0.1 on 2024-02-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0010_db_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='backup_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
