# Generated by Django 4.2.10 on 2024-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_server_uri', models.CharField(max_length=255)),
                ('server_connection_timeout', models.IntegerField(default=5000)),
                ('service_account_dn', models.CharField(max_length=255)),
                ('service_account_password', models.CharField(max_length=255)),
                ('default_login_domain', models.CharField(max_length=100)),
                ('user_search_base', models.CharField(max_length=255)),
                ('group_search_base', models.CharField(max_length=255)),
                ('users_object_class', models.CharField(max_length=100)),
                ('users_username_attribute', models.CharField(max_length=100)),
                ('users_login_attribute', models.CharField(max_length=100)),
                ('users_member_attribute', models.CharField(max_length=100)),
                ('users_search_attribute', models.CharField(max_length=255)),
                ('users_search_filter', models.CharField(max_length=255)),
                ('users_enable_attribute', models.CharField(max_length=100)),
                ('users_disabled_status_bitmask', models.IntegerField(default=2)),
                ('groups_object_class', models.CharField(max_length=100)),
                ('groups_name_attribute', models.CharField(max_length=100)),
                ('groups_member_user_attribute', models.CharField(max_length=100)),
                ('groups_search_attribute', models.CharField(max_length=100)),
                ('groups_search_filter', models.CharField(max_length=255)),
                ('groups_member_mapping_attribute', models.CharField(max_length=100)),
                ('groups_dn_attribute', models.CharField(max_length=100)),
                ('search_direct_nested', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
