# Generated by Django 4.2.10 on 2024-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedirectorysettings',
            name='server_connection_timeout',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activedirectorysettings',
            name='users_disabled_status_bitmask',
            field=models.IntegerField(max_length=255),
        ),
    ]
